version: '3'
services:
  pg:
    container_name: app-pg
    image: postgres:13-alpine
    environment:
      # NOTE: These variables are used only once - when setting up the database for the first time.
      # @see https://hub.docker.com/_/postgres/
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=apppass
      - POSTGRES_DB=app
      - POSTGRES_PORT=5432
    volumes:
      - app-pgdata:/var/lib/postgresql
    ports:
      - '5432:5432'
    networks:
      - app-network
  redis:
    image: redis
    container_name: app-cache
    ports:
      - '6379:6379'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  app-pgdata:
