@APP_URL = http://localhost:3000

###
GET {{APP_URL}}

### register user
POST {{APP_URL}}/registration
Content-Type: application/json

{
  "name": "widmo",
  "email": "widmo@rspective.pl",
  "password": "12345"
}

### login user
POST {{APP_URL}}/auth/login
Content-Type: application/json

{
  "username": "widmo@rspective.pl",
  "password": "12345"
}
