@APP_URL = http://localhost:8000

###
GET {{APP_URL}}

### register user
POST {{APP_URL}}/user/registration
Content-Type: application/json

{
  "name": "widmo",
  "email": "widomski.pawel@gmail.com",
  "password": "12345"
}

### reset user password
# @name reset-password
POST {{APP_URL}}/user/reset-password
Content-Type: application/json

{
  "email": "widomski.pawel@gmail.com"
}

### update user password
# @name update-password
PUT {{APP_URL}}/user/reset-password
Content-Type: application/json

{
  "userId": "a7b1af7d-43b7-4efa-b44d-c95f770b8f58",
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IndpZG9tc2tpLnBhd2VsQGdtYWlsLmNvbSIsImlhdCI6MTY3ODc5OTU0MSwiZXhwIjoxNjc4ODAzMTQxfQ.zKuY5ImThfvY2fK3IUbH7rrIRFs781LuCy8fdMgU7_c",
  "password": "12345"
}

### login user
# @name login
POST {{APP_URL}}/auth/login
Content-Type: application/json

{
  "username": "widomski.pawel@gmail.com",
  "password": "12345"
}

###
@authToken = {{login.response.body.authToken}}
### get current user
# @name get-user
GET {{APP_URL}}/user
Authorization: Bearer {{authToken}}
